footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 10 # 4.0
publish_frequency: 10 # 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 3.5
raytrace_range: 3.5

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser_front laser_rear
    laser_front: {data_type: LaserScan, clearing: true, marking: true, topic: realsense/scan, inf_is_valid: true, observation_persistence: 0.0}
    laser_rear: {data_type: LaserScan, clearing: true, marking: true, topic: realsense_rear/scan, inf_is_valid: true, observation_persistence: 0.0}

inflation:
    inflation_radius: 1.0
