# ekf base_link to odom
# example from https://github.com/mikeferguson/robomagellan/blob/ros2/config/ekf_local.yaml

odom_frame: odom
base_link_frame: base_link
world_frame: odom

publish_tf: true

two_d_mode: true

predict_to_current_time: true

frequency: 50

#odom0: /odom
#odom0_config: [false, false, false,   # x_pos,    y_pos,     z_pos
#               false, false, false,   # roll,     pitch,     yaw
#               true,  true,  false,   # x_vel,    y_vel,     z_vel
#               false, false, true,    # roll_vel, pitch_vel, yaw_vel
#               false, false, false]   # x_accel,  y_accel,   z_accel
#odom0_differential: false
#odom0_queue_size: 10

# zed cameras
# https://github.com/stereolabs/zed-ros-wrapper/issues/603

# for 1 zed camera

#odom1: /zed2i/zed_node/odom
#odom1_config: [true,  true,  false,   # x_pos,    y_pos,     z_pos
#               false, false, false,   # roll,     pitch,     yaw
#               false, false, false,   # x_vel,    y_vel,     z_vel
#               false, false, false,   # roll_vel, pitch_vel, yaw_vel
#               false, false, false]   # x_accel,  y_accel,   z_accel
#odom1_differential: false
#odom1_queue_size: 10

# 2 zed cameras
odom0: /zed_multi/zed2_front/zed_nodelet_front/odom
odom0_config: [true,  true,  false,   # x_pos,    y_pos,     z_pos
               false, false, true,    # roll,     pitch,     yaw
               false, false, false,   # x_vel,    y_vel,     z_vel
               false, false, false,   # roll_vel, pitch_vel, yaw_vel
               false, false, false]   # x_accel,  y_accel,   z_accel
odom0_differential: false
odom0_queue_size: 10

odom1: /zed_multi/zed2_front/zed_nodelet_rear/odom
odom1_config: [true,  true,  false,   # x_pos,    y_pos,     z_pos
               false, false, true,    # roll,     pitch,     yaw
               false, false, false,   # x_vel,    y_vel,     z_vel
               false, false, false,   # roll_vel, pitch_vel, ya w_vel
               false, false, false]   # x_accel,  y_accel,   z_accel
odom1_differential: false
odom1_queue_size: 10
# zed cameras

#odom0: /odometry/gps # change to /odometry/gps for real robot
#odom0_config: [true,  true,  false,   # x_pos,    y_pos,     z_pos
#               false, false, false,   # roll,     pitch,     yaw
#               false, false, false,   # x_vel,    y_vel,     z_vel
#               false, false, false,   # roll_vel, pitch_vel, yaw_vel
#               false, false, false]   # x_accel,  y_accel,   z_accel
#odom0_differential: false
#odom0_queue_size: 10

imu0: /imu/data
imu0_config: [false, false, false,   # x_pos,    y_pos,     z_pos
              true,  true,  true,    # roll,     pitch,     yaw
              false, false, false,   # x_vel,    y_vel,     z_vel
              true,  true,  true,    # roll_vel, pitch_vel, yaw_vel
              false, false, false]   # x_accel,  y_accel,   z_acce
imu0_differential: true
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true

imu1: /zed_multi/zed2_front/zed_nodelet_front/imu/data_raw 
imu1_config: [false, false, false,   # x_pos,    y_pos,     z_pos
              true,  true,  true,    # roll,     pitch,     yaw
              false, false, false,   # x_vel,    y_vel,     z_vel
              true,  true,  true,    # roll_vel, pitch_vel, yaw_vel
              false, false, false]   # x_accel,  y_accel,   z_acce
imu1_differential: true
imu1_queue_size: 10
imu1_remove_gravitational_acceleration: true

imu2: /zed_multi/zed2_rear/zed_nodelet_rear/imu/data_raw 
imu2_config: [false, false, false,   # x_pos,    y_pos,     z_pos
              true,  true,  true,    # roll,     pitch,     yaw
              false, false, false,   # x_vel,    y_vel,     z_vel
              true,  true,  true,    # roll_vel, pitch_vel, yaw_vel
              false, false, false]   # x_accel,  y_accel,   z_acce
imu2_differential: true
imu2_queue_size: 10
imu2_remove_gravitational_acceleration: true

