# ekf odom to map

# example from https://github.com/mikeferguson/robomagellan/blob/ros2/config/ekf_global.yaml
# and https://automaticaddison.com/sensor-fusion-using-the-ros-robot-pose-ekf-package/

odom_frame: odom
base_link_frame: base_link
world_frame: map
map_frame: map

publish_tf: true

two_d_mode: true

predict_to_current_time: true

frequency: 20 # 50

# wheel odom
odom0: /odom
odom0_config: [false, false, false,   # x_pos,    y_pos,     z_pos
               false, false, false,   # roll,     pitch,     yaw
               true,  true,  false,   # x_vel,    y_vel,     z_vel
               false, false, true,    # roll_vel, pitch_vel, yaw_vel
               false, false, false]   # x_accel,  y_accel,   z_accel
odom0_differential: false
odom0_queue_size: 10

odom1: /odometry/gps_front # change to /odometry/gps for real robot
odom1_config: [true,  true,  false,   # x_pos,    y_pos,     z_pos
               false, false, false,   # roll,     pitch,     yaw
               false, false, false,   # x_vel,    y_vel,     z_vel
               false, false, false,   # roll_vel, pitch_vel, yaw_vel
               false, false, false]   # x_accel,  y_accel,   z_accel
odom1_differential: false
#odom1_relative: true # new
odom1_queue_size: 10

#odom1: /odometry/gps # change to /odometry/gps for real robot
#odom1_config: [false, false, false,   # x_pos,    y_pos,     z_pos
#               false, false, true,    # roll,     pitch,     yaw
#               false, false, false,   # x_vel,    y_vel,     z_vel
#               false, false, false,   # roll_vel, pitch_vel, yaw_vel
#               false, false, false]   # x_accel,  y_accel,   z_accel
#odom1_differential: true
#odom1_relative: true # new
#odom1_queue_size: 10

# zed cameras
# https://github.com/stereolabs/zed-ros-wrapper/issues/603
#odom1: /zed_multi/zed2_front/zed_nodelet_front/odom
#odom1_config: [false, false, false,   # x_pos (true),    y_pos (true),     z_pos
#               false, false, true,    # roll,     pitch,     yaw
#               false, false, false,   # x_vel,    y_vel,     z_vel
#               false, false, false,   # roll_vel, pitch_vel, yaw_vel
#               false, false, false]   # x_accel,  y_accel,   z_accel
#odom1_differential: false
#odom1_queue_size: 10

#odom2: /zed_multi/zed2_rear/zed_nodelet_rear/odom
#odom2_config: [false, false, false,   # x_pos (true),    y_pos (true),     z_pos
#               false, false, true,    # roll,     pitch,     yaw
#               false, false, false,   # x_vel,    y_vel,     z_vel
#               false, false, false,   # roll_vel, pitch_vel, yaw_vel
#               false, false, false]   # x_accel,  y_accel,   z_accel
#odom2_differential: false
#odom2_queue_size: 10
# zed cameras

# if using laserscan amcl pose estimation 
#pose0: /amcl_pose
#pose0_config: [true, true,  false,   # x_pos,    y_pos,     z_pos
#              false, false, true,    # roll,     pitch,     yaw
#              false, false, false,   # x_vel,    y_vel,     z_vel
#              false, false, false,   # roll_vel, pitch_vel, yaw_vel
#              false, false, false]   # x_accel,  y_accel,   z_accel
#pose0_differential: false
#pose0_relative: true
#pose0_queue_size: 10

# only use amcl for yaw so can use 2d pose estinmation in rviz
#pose0: /amcl_pose
#pose0_config: [false, false,  false,   # x_pos,    y_pos,     z_pos
#               false, false,  true,    # roll,     pitch,     yaw
#               false, false,  false,   # x_vel,    y_vel,     z_vel
#               false, false,  false,   # roll_vel, pitch_vel, yaw_vel
#               false, false,  false]   # x_accel,  y_accel,   z_accel
#pose0_differential: false
#pose0_queue_size: 10

# zed cameras pose
# https://github.com/stereolabs/zed-ros-wrapper/issues/603
#pose0: /zed_multi/zed2_front/zed_nodelet_front/pose
#pose0_config: [false, false, false,   # x_pos (true),    y_pos (true),     z_pos
#               false, false, true,    # roll,     pitch,     yaw
#               false, false, false,   # x_vel,    y_vel,     z_vel
#               false, false, false,   # roll_vel, pitch_vel, yaw_vel
#               false, false, false]   # x_accel,  y_accel,   z_accel
#pose0_differential: false
#pose0_queue_size: 10

#pose1: /zed_multi/zed2_rear/zed_nodelet_front/pose
#pose1_config: [false, false, false,   # x_pos (true),    y_pos (true),     z_pos
#               false, false, true,    # roll,     pitch,     yaw
#               false, false, false,   # x_vel,    y_vel,     z_vel
#               false, false, false,   # roll_vel, pitch_vel, yaw_vel
#               false, false, false]   # x_accel,  y_accel,   z_accel
#pose1_differential: false
#pose1_queue_size: 10
# zed cameras pose

# pose/heading from the two gps recievers
pose0: /heading_pose
pose0_config: [false, false, false,   # x_pos,    y_pos,     z_pos
               false, false, true,    # roll,     pitch,     yaw
               false, false, false,   # x_vel,    y_vel,     z_vel
               false, false, false,   # roll_vel, pitch_vel, yaw_vel
               false, false, false]   # x_accel,  y_accel,   z_accel
pose0_differential: false
pose0_queue_size: 10

# pose/heading from fiducial slam
pose1: /fiducial_pose
pose1_config: [false, false, false,   # x_pos,    y_pos,     z_pos
               false, false, true,    # roll,     pitch,     yaw
               false, false, false,   # x_vel,    y_vel,     z_vel
               false, false, false,   # roll_vel, pitch_vel, yaw_vel
               false, false, false]   # x_accel,  y_accel,   z_accel
pose1_differential: true
pose1_queue_size: 10

imu0: /imu/data
imu0_config: [false, false, false,    # x_pos,    y_pos,     z_pos
              false, false, true,     # roll,     pitch,     yaw
              false, false, false,    # x_vel,    y_vel,     z_vel
              false, false, true,    # roll_vel, pitch_vel, yaw_vel
              true,  true,  false]    # x_accel,  y_accel,   z_acce
imu0_differential: true # false
imu0_relative: true # false
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true
imu0_pose_rejection_threshold: 0.8                
imu0_twist_rejection_threshold: 0.8                
imu0_linear_acceleration_rejection_threshold: 0.8  

# zed camera front imu
#imu1: /zed_multi/zed2_front/zed_nodelet_front/imu/data
#imu1_config: [false, false, false,   # x_pos,    y_pos,     z_pos
#              true,  true,  true,    # roll,     pitch,     yaw
#              false, false, false,   # x_vel,    y_vel,     z_vel
#              true,  true,  true,    # roll_vel, pitch_vel, yaw_vel
#              true,  true,  true]    # x_accel,  y_accel,   z_acce
#imu1_differential: false
#imu1_relative: true
#imu1_queue_size: 10
#imu1_remove_gravitational_acceleration: true

# zed camera rear imu
#imu2: /zed_multi/zed2_rear/zed_nodelet_rear/imu/data
#imu2_config: [false, false, false,   # x_pos,    y_pos,     z_pos
#              true,  true,  true,    # roll,     pitch,     yaw
#              false, false, false,   # x_vel,    y_vel,     z_vel
#              true,  true,  true,    # roll_vel, pitch_vel, yaw_vel
#              true,  true,  true]    # x_accel,  y_accel,   z_acce
#imu2_differential: false
#imu2_relative: true
#imu2_queue_size: 10
#imu2_remove_gravitational_acceleration: true

use_control: false

process_noise_covariance: [0.05, 0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                          0,    0.05, 0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                          0,    0,    0.05, 0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                          0,    0,    0,    0.05, 0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                          0,    0,    0,    0,    0.05, 0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                          0,    0,    0,    0,    0,    0.12, 0,     0,     0,    0,    0,    0,    0,    0,    0,
                          0,    0,    0,    0,    0,    0,    0.08, 0,     0,    0,    0,    0,    0,    0,    0,
                          0,    0,    0,    0,    0,    0,    0,     0.08, 0,    0,    0,    0,    0,    0,    0,
                          0,    0,    0,    0,    0,    0,    0,     0,     0.08, 0,    0,    0,    0,    0,    0,
                          0,    0,    0,    0,    0,    0,    0,     0,     0,    0.03, 0,    0,    0,    0,    0,
                          0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0.03, 0,    0,    0,    0,
                          0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0.07, 0,    0,    0,
                          0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0.01, 0,    0,
                          0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0.01, 0,
                          0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0.015]




initial_estimate_covariance: [1e-9, 0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                              0,    1e-9, 0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                              0,    0,    1e-9, 0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                              0,    0,    0,    0.03, 0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                              0,    0,    0,    0,    0.03, 0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                              0,    0,    0,    0,    0,    1e-9, 0,    0,    0,    0,     0,     0,     0,    0,    0,
                              0,    0,    0,    0,    0,    0,    1e-9, 0,    0,    0,     0,     0,     0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,    1e-9, 0,    0,     0,     0,     0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,    0,    1e-9, 0,     0,     0,     0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-9,  0,     0,     0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     1e-9,  0,     0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     1e-9,  0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     1e-9, 0,    0,
                              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    1e-9, 0,
                              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    1e-9]