# higher number = higher priority
topics:
- name    : joy
  topic   : joy_teleop/cmd_vel
  timeout : 0.5
  priority: 10
- name    : interactive_marker
  topic   : twist_marker_server/cmd_vel
  timeout : 0.5
  priority: 8
- name    : external
  topic   : cmd_vel
  timeout : 0.5
  priority: 1
- name    : bearnav2
  topic   : bearnav2/cmd_vel
  timeout : 0.5
  priority: 2
- name    : bearnav2_rear
  topic   : bearnav2_rear/cmd_vel
  timeout : 0.5
  priority: 1
- name    : move_base
  topic   : move_base/cmd_vel
  timeout : 0.5
  priority: 3